language: ruby
cache: bundler
rbenv:
- 2.4.1
services:
- postgresql
before_install:
- gem update --system
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec
deploy:
  provider: heroku
  app: cryptic-stream-22818
  on:
    repo: turing-coderdojo/coderdojo-BE
  api_key:
    secure: A7kyS9TSqi1EMkyixgpfdqvQqjSwZsW7aXiK9K2Ou271m9deNJ1g0xlILVbAoXK8at3zTkb99XmN5YLw64RNgGm0B8FeoXDX4k5XqIRQL8NOIajVS5R64kUEDMwsYN/Mab4zg0Ky1LFkg5J9zN5vANB3uoXi1I2ui1eaStMePAH2SoMXR4Rh46cCiQ52J9Da8VystFOLtcW0RpmwNitWCOvzZrVvWeoJUE+HCYcGLTitbVzwvCak4LG2Hq3XaGxP6n2SprjqNDnlLADrBd4IwRoXimkATflB3dJe5W/y01UEUXb1yR2ohCVbiCaRrdrh0x6cOkDzmkXk42AftcNmmNE6+LTNDRMGiiJG9X5fMrJ8Q+M9Di8KGlbjtjWMMvfkgBN0InDX6v7JbnSZkwbVHcYiBPOXLA6EaybKt/yhtRU2h6ssqwl6EsezcuQhKrWXVuodJEo8yKz99YDdpA05OljR8fTOhk6N9rOS8D5w0EW3iZlGNhQKMnHXit4b0I/mZhFzvbfj26+OV5pihMd5VnoEyiZq/Or0ROhfyK5Si5zL9eAbiClisaxngcc/cVujwP/rZgsT2amp9MoilYODKoPnff1v57EVv8Sm0shz5ZrRwYgGP1zTIGFkaoY2nJuJkxESsRXU1gO1uwWhOEl1KLOvxznNke8ad6zPi/iU/nU=
