language: ruby
cache: bundler
rbenv:
- 2.4.1
services:
- postgresql
before_install:
- gem update --system
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ORUo3CswWfGgSuQMb3A4QO01zajwQnclAKIG36r4PoYiFnKVCQIhnRm2OGAsXWzW2ax/9OyfKW1W05WV2tbs8FtEhpO9D++Mgpwea84IjkPBGrn3lut8PmWvwp5iR17SJlKpn8SnYTv6+Kxc64rJmZjxQbtnZVIzP2wcFlQOrKDN6Ow80ESYCV4SJ9JY/81qk9uyQBwWuGohoNIlKX0rjfJ2GuFf+d6F2SAMyG4EX1tTOwdimbxzfrtzcMlVaFR+ZScUHPjEl7g7JuGIORBI1cBaGwulvTEjsujvo58C2C5dsdkBQDjD161qyHFDqcolewuH7CTA6YUR0TTwg+dJACuWB2tkNdl7i/YFPeevWZy8a7FLYYcZJvhXghA7AKKuir/8rZyuPae7SPLDd8BfJap+P8A7y3bjtqYGNaVdw41PGK1jZpzPxgedXd/raU2M/MuftSh2LpDwuSJvcG1ho6WuhbjZPdvnWRwCb1gkZEBmcj/Iz8+5yXhzGLcUgx3aBRW/jDgy/Cpt2bEc0X8Qf0zLwBmIXfEvC34Hk+3iRoDcMfPJRfQ085BAXMSQcCioU1l73aReUyDUDUoZlqjJWWcvHBL2ZPbKzUtmiXRaz5/Jl2vHyn1h19XqWggpv/vFeSncy63kDSWf5osL0XN8mKyZahfja6FQWafKVwphO/o=
