# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).


superuser_1 = User.create(name: "Ian Douglas", username: "ian.douglas", email: "ian.douglas@iandouglas.com", password: "aaawtf", role: 3)
superuser_2 = User.create(name: "Steve Thompson", username: "scthomps312", email: "scthomps312@gmail.com", password: "aaawtf", role: 3)
superuser_3 = User.create(name: "Joe Haynes", username: "jphaynes", email: "jphaynes1966@gmail.com", password: "aaawtf", role: 3)

venue_1 = Venue.create(name: "CoderDojo Denver")
venue_2 = Venue.create(name: "MakerDojo Denver")

VenueAdmin.create(user_id: superuser_1.id, venue_id: venue_1.id)
VenueAdmin.create(user_id: superuser_1.id, venue_id: venue_2.id)
VenueAdmin.create(user_id: superuser_2.id, venue_id: venue_1.id)
VenueAdmin.create(user_id: superuser_3.id, venue_id: venue_1.id)

venue_1.addresses.create(street_1: "1331 17th St", street_2: "Suite LL-100", city: "denver", state: "CO", zip: "80202")
venue_2.addresses.create(street_1: "1331 17th St", street_2: "Suite LL-100", city: "denver", state: "CO", zip: "80202")

# admin_1 = User.create(name: "Admin One", username: "admin1", email: "example@admin1.com", password: "password", role: 2, phone_number: "5555555553")
# admin_2 = User.create(name: "Admin Two", username: "admin2", email: "example@admin2.com", password: "password", role: 2, phone_number: "5555555515")
# admin_3 = User.create(name: "Admin Three", username: "admin3", email: "example@admin3.com", password: "password", role: 2, phone_number: "5555555525")
# user_1 = User.create(name: "Matt Weiss", username: "Duce", email: "weiss.matt@outlook.com", password: "password", role: 1, phone_number: "5555555555")
#
# student_1 = User.create(name: "Student One", username: "student1", email: "example@student.com", password: "password", role: 0, birthdate: "Jan 1, 2005", guardian_id: user_1.id)
# student_2 = User.create(name: "Student Two", username: "student2", email: "example2@student2.com", password: "password", role: 0, birthdate: "Jan 1, 2006", guardian_id: user_1.id)
#
# student_3 = User.create(name: "Student Three", username: "student3", email: "example3@student3.com", password: "password", role: 0, birthdate: "Jan 1, 2007", guardian_id: admin_1.id)
# student_4 = User.create(name: "Student Four", username: "student4", email: "example4@student4.com", password: "password", role: 0, birthdate: "Jan 1, 2008", guardian_id: admin_1.id)
# student_5 = User.create(name: "Student Five", username: "student5", email: "example5@student5.com", password: "password", role: 0, birthdate: "Jan 1, 2009", guardian_id: admin_1.id)
#
# venue_1 = Venue.create(name: "Venue One", notes: "Here be Dragons", email: "example@venue.com", web_url: "www.venueone.com")
# venue_2 = Venue.create(name: "Venue Two", email: "example@venue2.com", web_url: "www.venuetwo.com")
# venue_3 = Venue.create(name: "Venue Three", notes: "This basement has no windows", email: "example@venue3.com", web_url: "www.venuethree.com")
#
# user_1.addresses.create(street_1: "123 Main St.", street_2: "Apt 345", city: "denver", state: "CO", zip: "80128")
# admin_1.addresses.create(street_1: "234 Main St.", street_2: "Apt 456", city: "denver", state: "CO", zip: "80128")
# superuser_1.addresses.create(street_1: "456 Main St.", street_2: "Apt 567", city: "denver", state: "CO", zip: "80128")
# venue_1.addresses.create(street_1: "567 Main St.", street_2: "Apt 678", city: "denver", state: "CO", zip: "80128")
# venue_2.addresses.create(street_1: "567 Main St.", street_2: "Apt 678", city: "denver", state: "CO", zip: "80128")
# venue_3.addresses.create(street_1: "567 Main St.", street_2: "Apt 678", city: "denver", state: "CO", zip: "80128")
#
# VenueAdmin.create(user_id: admin_1.id, venue_id: venue_1.id)
# VenueAdmin.create(user_id: admin_2.id, venue_id: venue_2.id)
# VenueAdmin.create(user_id: admin_2.id, venue_id: venue_3.id)
# VenueAdmin.create(user_id: admin_3.id, venue_id: venue_3.id)
#
# event_1 = venue_2.events.create(name: "Test Event 1", start_time: '2019-08-21 17:00:00', end_time: '2019-08-19 18:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_2 = venue_1.events.create(name: "Test Event 2", start_time: '2019-08-21 17:00:00', end_time: '2019-08-21 18:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_3 = venue_1.events.create(name: "Test Event 3", start_time: '2019-08-22 17:00:00', end_time: '2019-08-22 18:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_4 = venue_1.events.create(name: "Test Event 4", start_time: '2019-08-23 19:00:00', end_time: '2019-08-23 20:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_5 = venue_1.events.create(name: "Test Event 5", start_time: '2019-07-18 19:00:00', end_time: '2019-07-18 20:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_6 = venue_1.events.create(name: "Test Event 6", start_time: '2019-07-17 19:00:00', end_time: '2019-07-17 20:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
# event_7 = venue_1.events.create(name: "Test Event 7", start_time: '2019-07-16 19:00:00', end_time: '2019-07-16 20:00:00', notes: "testing notes", event_code: SecureRandom.hex(3))
#
# event_6.addresses.create(street_1: "567 Different St.", street_2: "Apt 678", city: "Denver", state: "CO", zip: "80128")
#
# UserEvent.create(user_id: student_1.id, event_id: event_1.id)
# UserEvent.create(user_id: student_2.id, event_id: event_1.id)
# UserEvent.create(user_id: student_3.id, event_id: event_1.id)
# UserEvent.create(user_id: student_4.id, event_id: event_1.id)
# UserEvent.create(user_id: student_5.id, event_id: event_1.id)
# UserEvent.create(user_id: student_1.id, event_id: event_2.id)
# UserEvent.create(user_id: student_1.id, event_id: event_3.id)
# UserEvent.create(user_id: student_2.id, event_id: event_2.id)
# UserEvent.create(user_id: student_2.id, event_id: event_3.id)
# UserEvent.create(user_id: student_3.id, event_id: event_3.id)
# UserEvent.create(user_id: student_4.id, event_id: event_4.id)
#
# goal_1 = Goal.create(category: "Attendance", name: "First Class", description: "Attend 1 session", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_2 = Goal.create(category: "Attendance", name: "High Five", description: "Attend 5 sessions", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_3 = Goal.create(category: "Attendance", name: "Ten Something", description: "Attend 10 sessions", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_4 = Goal.create(category: "Attendance", name: "Clever Twenty Pun", description: "Attend 20 sessions", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_5 = Goal.create(category: "Proficiency", name: "First Lesson", description: "Complete Novice Lesson", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_6 = Goal.create(category: "Proficiency", name: "Learning More", description: "Complete Intermediate Lesson", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_7 = Goal.create(category: "Proficiency", name: "Finish Scratch", description: "Complete Expert Lesson", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_8 = Goal.create(category: "Behavior", name: "Helper", description: "Help 1 fellow student", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_9 = Goal.create(category: "Behavior", name: "Leader", description: "Lead a group project", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
# goal_10 = Goal.create(category: "Behavior", name: "Organizer", description: "Help instructor pack up after class", img_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png")
#
# achievement_1 = venue_1.achievements.create(name: "Venue 1 Achv 1", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_2 = venue_1.achievements.create(name: "Venue 1 Achv 2", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_3 = venue_1.achievements.create(name: "Venue 1 Achv 3", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_4 = venue_1.achievements.create(name: "Venue 1 Achv 4", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_5 = venue_2.achievements.create(name: "Venue 2 Achv 1", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_6 = venue_2.achievements.create(name: "Venue 2 Achv 2", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_7 = venue_2.achievements.create(name: "Venue 2 Achv 3", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_8 = venue_3.achievements.create(name: "Venue 3 Achv 1", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_9 = venue_3.achievements.create(name: "Venue 3 Achv 2", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
# achievement_10 = venue_3.achievements.create(name: "Venue 3 Achv 3", badge_url: "https://cdn3.iconfinder.com/data/icons/project-development-2/128/milestone-2-512.png", description: "Achievement info here")
#
# ach_goal_1 = AchievementGoal.create(achievement_id: achievement_1.id, goal_id: goal_1.id)
# ach_goal_2 = AchievementGoal.create(achievement_id: achievement_1.id, goal_id: goal_5.id)
# ach_goal_3 = AchievementGoal.create(achievement_id: achievement_2.id, goal_id: goal_2.id)
# ach_goal_4 = AchievementGoal.create(achievement_id: achievement_2.id, goal_id: goal_6.id)
# ach_goal_5 = AchievementGoal.create(achievement_id: achievement_3.id, goal_id: goal_3.id)
# ach_goal_6 = AchievementGoal.create(achievement_id: achievement_3.id, goal_id: goal_7.id)
#
# ach_goal_7 = AchievementGoal.create(achievement_id: achievement_4.id, goal_id: goal_1.id)
# ach_goal_8 = AchievementGoal.create(achievement_id: achievement_4.id, goal_id: goal_5.id)
# ach_goal_9 = AchievementGoal.create(achievement_id: achievement_5.id, goal_id: goal_2.id)
# ach_goal_10 = AchievementGoal.create(achievement_id: achievement_5.id, goal_id: goal_6.id)
# ach_goal_11 = AchievementGoal.create(achievement_id: achievement_6.id, goal_id: goal_3.id)
# ach_goal_12 = AchievementGoal.create(achievement_id: achievement_6.id, goal_id: goal_7.id)
# ach_goal_13 = AchievementGoal.create(achievement_id: achievement_7.id, goal_id: goal_4.id)
# ach_goal_14 = AchievementGoal.create(achievement_id: achievement_7.id, goal_id: goal_8.id)
# ach_goal_15 = AchievementGoal.create(achievement_id: achievement_7.id, goal_id: goal_10.id)
#
# ach_goal_16 = AchievementGoal.create(achievement_id: achievement_8.id, goal_id: goal_1.id)
# ach_goal_17 = AchievementGoal.create(achievement_id: achievement_8.id, goal_id: goal_5.id)
# ach_goal_18 = AchievementGoal.create(achievement_id: achievement_9.id, goal_id: goal_2.id)
# ach_goal_19 = AchievementGoal.create(achievement_id: achievement_9.id, goal_id: goal_6.id)
# ach_goal_20 = AchievementGoal.create(achievement_id: achievement_10.id, goal_id: goal_3.id)
# ach_goal_21 = AchievementGoal.create(achievement_id: achievement_10.id, goal_id: goal_7.id)
# ach_goal_22 = AchievementGoal.create(achievement_id: achievement_10.id, goal_id: goal_9.id)
#
# student_achv_goal_1 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_1.id, started_at: '2019-08-21 17:00:00', completed_at: '2019-08-21 17:00:00')
# student_achv_goal_2 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_2.id, started_at: '2019-08-21 17:00:00', completed_at: '2019-08-21 18:00:00')
# student_achv_goal_3 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_3.id, started_at: '2019-08-21 17:00:00', completed_at: '2019-08-21 18:00:00')
# student_achv_goal_4 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_4.id, started_at: '2019-08-21 17:00:00')
# student_achv_goal_5 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_5.id, started_at: '2019-08-21 17:00:00')
# student_achv_goal_6 = StudentAchvGoal.create(user_id: student_1.id, achievement_goal_id: ach_goal_6.id, started_at: '2019-08-21 17:00:00')
